# Microsoft Graph API Configuration
azure:
  activedirectory:
    # Your Azure AD Application (client) ID
    client-id:  asda

    # Your Azure AD Tenant (directory) ID
    tenant-id: aada

    # Your Azure AD Client Secret Value (copied immediately after creation)
    client-secret: asddf

# Application-specific configuration
graph:
  sender-email: asdf # IMPORTANT: Replace with the actual email address of the mailbox you want to send from
  tracking-base-url: http://localhost:8080



# --- SMTP Configuration (Required for Fallback) ---
spring:
  mail:
    host: smtp.office365.com # e.g., smtp.office365.com, smtp.gmail.com
    port: 587 # or 465 for SSL/TLS
    username: asdf # The sender's email address
    password: asdf # The sender's app-specific password or regular password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # Use STARTTLS for secure connection
          connectiontimeout: 5000 # 5 seconds
          timeout: 10000
          writetimeout: 10000
